### PR TITLE
Update feature-matrix.md

### PR DESCRIPTION
**Pull request by larsiusprime**
Just a quick run through. I'm pretty sure all these are done. I'm sure there's more I've missed that could be flipped to "yes" too.

### CODE REVIEW

**Comment by larsiusprime** [comment]
do double check I didn't make a mistake :) I went through the code to
verify, but I did see some "//TODO: verify this works" comments that I
assume are fairly old now?

On Wed, Aug 26, 2015 at 8:12 PM, Nilsen Filc <notifications@github.com>
wrote:

> Merged #48 <https://github.com/openfl/openfl.org/pull/48>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openfl/openfl.org/pull/48#event-393509836>.
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by Hasufel** [comment]
maybe specify those todos in here so that we make sure

**Comment by larsiusprime** [comment]
Sure, looks like search finds them:

https://github.com/openfl/openfl/search?utf8=%E2%9C%93&q=todo

Seems mostly related to tests. Do we have those in continuous integration (travis or whatever we're using) already?

**Comment by larsiusprime** [comment]
Double-check:

- Capabilities
- System
- URLLoader

**Comment by Hasufel** [comment]
- Capabilities, screenResolutionX + screenResolutionY confirmed, need to check for language

**Comment by Hasufel** [comment]
- getColorBoundsRect: _confirmed_
- draw: _confirmed_
- joystick: _confirmed_

**Comment by Hasufel** [comment]
- Capabilites, language: _confirmed_

**Pull request merged**
