### PR TITLE
update linux download link

### PR DESCRIPTION
**Pull request by andyli**
point to haxe.org linux packages page

### CODE REVIEW

**Comment by jgranick** [comment]
Hi @andyli 

There has been problems in the past with Haxe being partially installed on Linux, but missing either proper Neko support (any library that uses CFFI fails due to missing libraries) or being an old version that is incompatible.

I'm hesitant (but excited) to point developer to PPAs and other kinds of official paths rather than our own shell script, but only if it is reliable. Is Haxe 3.2.1 available in all these channels? Have they been tested with libraries like OpenFL?

Is haxelib setup with user read/write permissions after install on these, and is it haxelib as a Neko binary, not as a Haxe interp?

Thank you :smile:

**Comment by andyli** [comment]
> partially installed on Linux, but missing either proper Neko support (any library that uses CFFI fails due to missing libraries) or being an old version that is incompatible

That's exactly what package systems are trying to solve - they allow us to properly define software dependencies, such that installing haxe will always install a compatible version of neko.
Having a custom install script for OpenFL is just going to make things worse: one more way of installing haxe/neko and we have to ask people what way they're used when they have trouble. And, OpenFL's script doesn't provide a way to uninstall/upgrade, which all Linux package managers support out of the box.

> Is Haxe 3.2.1 available in all these channels?

Yes. Haxe 3.2.1 is available for all the distros listed in http://haxe.org/download/linux.

> Have they been tested with libraries like OpenFL?

I've manually tested with the OpenFL DisplayingABitmap sample. Works as expected.
If there is anything that doesn't work with our linux packages, please report to us.

> Is haxelib setup with user read/write permissions after install on these

As documented in http://haxe.org/download/linux, `haxelib setup` should be run manually after installation. We suggested using `~/haxelib`, which is writable by the user by default. One can still use `/usr/lib/haxe/lib`, but shouldn't change its permission since it is indeed a system directory.

> is it haxelib as a Neko binary, not as a Haxe interp?

It is a nekotools booted binary. There are a few issues with Haxe --interp, so we decided to move away from it.

**Comment by jgranick** [comment]
Hi Andy,

I have tested your PPA for Ubuntu, and it appears to work properly. Prior to your ongoing effort to maintain current and stable Haxe releases for different *nix systems, either the official packages for Haxe and Neko were hopelessly out-of-date, or as mentioned previously, the packages were broken, such that using Neko native shared libraries would result in a crash.

I am prepared to recommend your Linux packages instead of our historic install script. You may not know our script started a very long time ago when there was no Haxe installer for Linux, and packages were non-existant or unreliable. We tested official packages as recently as Haxe 3.4.2 (I believe), but that was not using the PPA.

It was recently noted that there was a "passive aggressive" tussle between the Haxe Linux download page and our own. I would like to see if the `**WARNING**` message on the Haxe Linux download page could be removed? I would be happy to merge your pull request afterward.

Thanks again for all your work

**Comment by jgranick** [comment]
@andyli Do you think it would be possible to remove that warning message from the Linux download page?

**Comment by andyli** [comment]
> Do you think it would be possible to remove that warning message from the Linux download page?

Sure. As soon as OpenFL's installer script is removed, I will take care of removing the haxe.org download page warning.

**Comment by andyli** [comment]
Closing this PR since there is a conflict anyway. Feel free to ping me whenever the installer script is removed.

**Pull request closed without merging**
