### PR TITLE
add XSD for OpenFL XML project descriptor

### PR DESCRIPTION
**Pull request by sebthom**
I created an XSD file one can use to enable XML auto completion and validation in editors supporting this.

### CODE REVIEW

**Review by loudoweb — COMMENTED** [review]
Thank you for your contribution (and sorry for the time it took)
Works great but there are some missing tags
* define
* undefine
* set
* unset
* library
* echo

I'll try to add this myself but I may need you as I don't know very well xsd

**Comment by loudoweb** [comment]
Since the xml format page has been moved to lime.software website, maybe it's better to put the xsd file on lime website.

**Comment by sebthom** [comment]
True, a lot has change in the last six years this PR is waiting for being merged :-) 
So nowadays the XSD may actually be better placed in one of the repos at https://github.com/haxelime

**Comment by loudoweb** [comment]
thanks @sebthom, I've also added other tags and attributes. Better late than nothing :)

https://lime.software/xsd/project-1.0.0.xsd

**Pull request closed without merging**
